<a href="https://colab.research.google.com/github/Sreenivas77-star/Python/blob/main/NP2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
class NDarray:
  def __init__(self,arr):
    self.arr = arr
    self.shape = arr.shape

In [5]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [7]:
#reshape

arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
arr.reshape(8,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [15]:
arr.ndim

1

In [16]:
arr.itemsize

8

In [17]:
arr.dtype

dtype('int64')

In [21]:
arr1 = np.arange(10,dtype=np.int32)
arr2 = np.arange(12,dtype=np.float32).reshape(3,4)
arr3 = np.arange(8).reshape(2,2,2)

In [23]:
arr3.astype(np.float32)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]], dtype=float32)

In [29]:
#Scalar operastion

arr3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [33]:
arr3+2

array([[[2, 3],
        [4, 5]],

       [[6, 7],
        [8, 9]]])

In [38]:
arr3-2

array([[[-2, -1],
        [ 0,  1]],

       [[ 2,  3],
        [ 4,  5]]])

In [40]:
arr1+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [39]:
arr2*5

array([[ 60,  65,  70,  75],
       [ 80,  85,  90,  95],
       [100, 105, 110, 115]])

In [45]:
#vector Operations
arr1 =np.arange(12).reshape(3,4)
arr2 =np.arange(12,24).reshape(3,4)
arr1,arr2


(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [46]:
arr1+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [47]:
arr1*arr2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [48]:
arr1/arr2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [55]:
arr1 = np.random.random((3,3))
arr1

array([[0.72674857, 0.89515327, 0.41761865],
       [0.99402503, 0.35699632, 0.25836327],
       [0.676129  , 0.97903234, 0.73192711]])

In [56]:
np.around(arr1,2)

array([[0.73, 0.9 , 0.42],
       [0.99, 0.36, 0.26],
       [0.68, 0.98, 0.73]])

In [57]:
np.sin(arr1)

array([[0.66444323, 0.78030494, 0.40558491],
       [0.83822769, 0.34946151, 0.25549849],
       [0.62577833, 0.82995797, 0.66830443]])

In [58]:
np.exp(arr1)

array([[2.06834458, 2.44771092, 1.51834154],
       [2.70208861, 1.42903061, 1.2948091 ],
       [1.96625161, 2.66187921, 2.07908337]])

In [59]:
np.log(arr1)

array([[-0.31917471, -0.11076033, -0.87318659],
       [-0.00599289, -1.0300298 , -1.35338865],
       [-0.3913714 , -0.0211906 , -0.31207435]])