<a href="https://colab.research.google.com/github/Sreenivas77-star/Python/blob/main/NP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a2 = a1
print(a1)
a2[2] = 4
print(a2)
#print(a1)

[1 2 3]
[1 2 4]


In [4]:
x = np.arange(10)
#x
y = np.array([100,200]) # creates a View
#y
y[0:1] = [10,11]
x
#y

ValueError: could not broadcast input array from shape (2,) into shape (1,)

In [5]:
arr5 = np.arange(10).reshape(5,2)
arr5

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
arr5.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#array Operations
#scalar Operation
#Vector Operation

In [ ]:
#Scalar Operations

In [9]:
arr1 = np.arange(12).reshape(3,4)
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
arr1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [11]:
arr1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [12]:
arr1+5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [14]:
arr1 == 5

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False]])

In [15]:
arr1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [16]:
arr1!=2

array([[ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [17]:
arr1>2

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [18]:
arr1//2

array([[0, 0, 1, 1],
       [2, 2, 3, 3],
       [4, 4, 5, 5]])

In [19]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12,24).reshape(3,4)


In [20]:
arr1,arr2

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]))

In [21]:
arr1*arr2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

In [22]:
arr1-arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [23]:
arr1/arr2

array([[0.        , 0.07692308, 0.14285714, 0.2       ],
       [0.25      , 0.29411765, 0.33333333, 0.36842105],
       [0.4       , 0.42857143, 0.45454545, 0.47826087]])

In [24]:
arr1+arr2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [ ]:
#array Functions

In [ ]:
#rouns,min,max,sum,prod,floor,round,ceil,trigonomentry,log,exp

In [25]:
arr6 = np.arange(12).reshape(3,4)
arr6

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.amin(arr6)

0

In [29]:
np.max(arr6)

11

In [30]:
sum(arr6)

array([12, 15, 18, 21])

In [33]:
np.prod(arr6,axis=1)

array([   0,  840, 7920])

In [34]:
np.sum(arr6,axis=0)#coloumnd -0 rows -1

array([12, 15, 18, 21])

In [35]:
np.round(np.sqrt(arr6),2)

array([[0.  , 1.  , 1.41, 1.73],
       [2.  , 2.24, 2.45, 2.65],
       [2.83, 3.  , 3.16, 3.32]])

In [36]:
np.floor(np.sqrt(arr6))

array([[0., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 3., 3., 3.]])

In [37]:
np.ceil(np.sqrt(arr6))

array([[0., 1., 2., 2.],
       [2., 3., 3., 3.],
       [3., 3., 4., 4.]])

In [38]:
np.sin(arr6)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [39]:
np.log(arr6)

<ipython-input-39-70e243a08446>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr6)


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [40]:
np.mean(arr6)

5.5

In [41]:
np.skew(arr6)

AttributeError: module 'numpy' has no attribute 'skew'

In [42]:
np.median(arr6)

5.5

In [43]:
np.mode(arr6)

AttributeError: module 'numpy' has no attribute 'mode'

In [44]:
np.exp(arr6)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

In [74]:
#indexing
#Slicing

arr1 = np.arange(10)
arr2 = np.arange(12,dtype = np.float32).reshape(3,4)
arr3 = np.arange(16).reshape(2,4,2)

In [63]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [51]:
arr1[9]

9

In [54]:
arr2[0]

0.0

In [56]:
#arr[row,col]
#arr[start:end:stride,start:end:stride]

In [65]:
arr2[0:2]

array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]], dtype=float32)

In [66]:
arr2[0:3:2,1:4:2]

array([[ 1.,  3.],
       [ 9., 11.]], dtype=float32)

In [69]:
arr2[1:3,:2]

array([[4., 5.],
       [8., 9.]], dtype=float32)

In [73]:
arr2[1:3,1:4:2]

array([[ 5.,  7.],
       [ 9., 11.]], dtype=float32)

In [ ]:
arr2[]

In [79]:
arr3 = np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [76]:
arr3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [81]:
arr3[0:2,0]

array([[ 0,  1,  2],
       [ 9, 10, 11]])

In [82]:
arr3[2]

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

In [85]:
arr3[2,:,0:1:2]

array([[18],
       [21],
       [24]])

In [86]:
arr3[2,2:4]

array([[24, 25, 26]])