<a href="https://colab.research.google.com/github/Sreenivas77-star/Python/blob/main/NP5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np

In [43]:
arr1 = np.random.randint(1,1000,15)
arr1

array([138, 608,  20, 186, 262, 871, 525, 161, 372, 910, 275, 599, 450,
       817,  17])

In [44]:
arr1.reshape(5,3)

array([[138, 608,  20],
       [186, 262, 871],
       [525, 161, 372],
       [910, 275, 599],
       [450, 817,  17]])

In [45]:
arr1.shape

(15,)

In [46]:
np.sort(arr1)

array([ 17,  20, 138, 161, 186, 262, 275, 372, 450, 525, 599, 608, 817,
       871, 910])

In [47]:
np.sort(arr1)[-1]

910

In [49]:
arr2 = np.random.randint(1,100,30).reshape(6,5)
arr2

array([[80, 82, 15,  6, 79],
       [81, 26, 90, 70, 49],
       [ 4, 75, 94, 97, 50],
       [18, 83, 53, 25, 53],
       [85, 50, 50, 91, 95],
       [53, 23, 57, 62,  5]])

In [50]:
np.sort(arr2)

array([[ 6, 15, 79, 80, 82],
       [26, 49, 70, 81, 90],
       [ 4, 50, 75, 94, 97],
       [18, 25, 53, 53, 83],
       [50, 50, 85, 91, 95],
       [ 5, 23, 53, 57, 62]])

In [51]:
np.sort(arr2,axis=0)

array([[ 4, 23, 15,  6,  5],
       [18, 26, 50, 25, 49],
       [53, 50, 53, 62, 50],
       [80, 75, 57, 70, 53],
       [81, 82, 90, 91, 79],
       [85, 83, 94, 97, 95]])

In [52]:
np.sort(arr2,axis=0)[::-1]

array([[85, 83, 94, 97, 95],
       [81, 82, 90, 91, 79],
       [80, 75, 57, 70, 53],
       [53, 50, 53, 62, 50],
       [18, 26, 50, 25, 49],
       [ 4, 23, 15,  6,  5]])

In [53]:
#append
arr1

array([138, 608,  20, 186, 262, 871, 525, 161, 372, 910, 275, 599, 450,
       817,  17])

In [57]:
arr1.append[101]

AttributeError: 'numpy.ndarray' object has no attribute 'append'

In [55]:
arr2

array([[80, 82, 15,  6, 79],
       [81, 26, 90, 70, 49],
       [ 4, 75, 94, 97, 50],
       [18, 83, 53, 25, 53],
       [85, 50, 50, 91, 95],
       [53, 23, 57, 62,  5]])

In [56]:
np.append(arr2,np.random.randint(1,100,6).reshape(6,1),axis=1)

array([[80, 82, 15,  6, 79,  8],
       [81, 26, 90, 70, 49, 32],
       [ 4, 75, 94, 97, 50, 88],
       [18, 83, 53, 25, 53, 75],
       [85, 50, 50, 91, 95, 38],
       [53, 23, 57, 62,  5, 62]])

In [58]:
arr3 = np.random.randint(1,100,24).reshape(6,4)
arr3

array([[34, 22, 34, 90],
       [10, 99, 27, 60],
       [58, 39, 89, 61],
       [42, 14, 87, 45],
       [71, 40, 15, 95],
       [70, 94,  1,  1]])

In [59]:
arr4 = np.random.randint(100,200,24).reshape(6,4)
arr4

array([[191, 136, 137, 144],
       [122, 174, 179, 154],
       [114, 134, 113, 183],
       [113, 197, 185, 104],
       [160, 126, 190, 116],
       [170, 148, 118, 189]])

In [60]:
np.concatenate((arr3,arr4),axis=1)

array([[ 34,  22,  34,  90, 191, 136, 137, 144],
       [ 10,  99,  27,  60, 122, 174, 179, 154],
       [ 58,  39,  89,  61, 114, 134, 113, 183],
       [ 42,  14,  87,  45, 113, 197, 185, 104],
       [ 71,  40,  15,  95, 160, 126, 190, 116],
       [ 70,  94,   1,   1, 170, 148, 118, 189]])

In [61]:
import random

In [62]:
n=100
lst = []
for i in range(n):
  random.choice([1,2,3])
lst.append(random.choice[1,2,3])

TypeError: 'method' object is not subscriptable

In [37]:
#Unique

arr5 = np.array(lst)

In [38]:
len(np.unique(arr5))

0

In [41]:
arr1

array([594, 378, 920, 114, 382, 962, 931, 552, 386, 293, 178, 363, 402,
       869, 940])

In [40]:
np.where(arr1<20)

(array([], dtype=int64),)

In [63]:
np.max(arr1)

910

In [64]:
np.argmax(arr1)

9

In [69]:
np.append(arr1,1)


array([138, 608,  20, 186, 262, 871, 525, 161, 372, 910, 275, 599, 450,
       817,  17,   1])

In [70]:
lst = [138, 608,  20, 186, 262, 871, 525, 161, 372, 910, 275, 599, 450,
       817,  17,   1]
       arr6 = np.array

In [71]:
arr2

array([[80, 82, 15,  6, 79],
       [81, 26, 90, 70, 49],
       [ 4, 75, 94, 97, 50],
       [18, 83, 53, 25, 53],
       [85, 50, 50, 91, 95],
       [53, 23, 57, 62,  5]])

In [72]:
np.argmax(arr2)

13

In [73]:
np.max(arr2)

97

In [74]:
np.argmax(arr2,axis=1)

array([1, 2, 3, 1, 4, 3])

In [75]:
arr1

array([138, 608,  20, 186, 262, 871, 525, 161, 372, 910, 275, 599, 450,
       817,  17])

In [76]:
np.cumsum(arr1)

array([ 138,  746,  766,  952, 1214, 2085, 2610, 2771, 3143, 4053, 4328,
       4927, 5377, 6194, 6211])

In [77]:
arr2

array([[80, 82, 15,  6, 79],
       [81, 26, 90, 70, 49],
       [ 4, 75, 94, 97, 50],
       [18, 83, 53, 25, 53],
       [85, 50, 50, 91, 95],
       [53, 23, 57, 62,  5]])

In [78]:
np.cumsum(arr2,axis=1)

array([[ 80, 162, 177, 183, 262],
       [ 81, 107, 197, 267, 316],
       [  4,  79, 173, 270, 320],
       [ 18, 101, 154, 179, 232],
       [ 85, 135, 185, 276, 371],
       [ 53,  76, 133, 195, 200]])

In [79]:
np.cumprod(arr1)

array([                 138,                83904,              1678080,
                  312122880,          81776194560,       71227065461760,
          37394209367424000,  6020467708155264000,  7557954514902462464,
       -2896930932421910528, -3446011246514675712,  1874599593179029504,
       -4980410460076097536,  7735094407639220224,  2369396413899882496])

In [81]:
np.percentile(arr1,50)

372.0

In [82]:
np.percentile(arr1,75)

603.5

In [86]:
len(arr1)

15

In [88]:
sum(np.where(arr1<75,True,False))

2

In [89]:
4/15

0.26666666666666666

In [91]:
lst = [1,2,10,-100]
arr = np.array(lst)
arr

array([   1,    2,   10, -100])

In [92]:
np.all(arr)

True

In [94]:
np.isin(arr,1)

array([ True, False, False, False])

In [99]:
import matplotlib.pyplot as plt
from PIL import Image