<a href="https://colab.research.google.com/github/Sreenivas77-star/Python/blob/main/Pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [5]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
y = x[1,2]
y

5

In [7]:
import numpy as np

x = np.ones((2,3))
x

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
x.T


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
import pandas as pd

In [15]:
# creating series

students = ['Alice', 'Jack', 'Molly']
pd.Series(students)

0    Alice
1     Jack
2    Molly
dtype: object

In [17]:
age = [20,21,19]
pd.Series(age)

0    20
1    21
2    19
dtype: int64

In [18]:
pd.Series([100,99,98],index=students)

Alice    100
Jack      99
Molly     98
dtype: int64

In [28]:
#Create from dict
students_scores = {'Alice': 'Physics',
                   'jack': 'Chemistry',
                   'Molly': 'English'}
s = pd.Series(students_scores)
s

Alice      Physics
jack     Chemistry
Molly      English
dtype: object

In [36]:
students_scores = {'Alice': 100.0,
                   'jack': 99,
                   'Molly': 98}
s2 = pd.Series(students_scores)
s2

Alice    100.0
jack      99.0
Molly     98.0
dtype: float64

In [ ]:
#attributes

In [25]:
s.size

3

In [30]:
s2.dtype

dtype('float64')

In [31]:
s2.index

Index(['Alice', 'jack', 'Molly'], dtype='object')

In [37]:
s2.is_unique #if chanhge to same values it will be false

True